#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header X-Served-By

apt-get update -y
apt-get install nginx -y

HOSTNAME=$(hostname)

grep -q "X-Served-By" /etc/nginx/sites-available/default || \
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default

service nginx restart
