#!/usr/bin/env bash
# Installs and configures HAProxy as a load balancer for web-01 and web-02

apt-get update -y
apt-get install haproxy -y

cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
    log /dev/log local0
    maxconn 2048
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7042-web-01 3.84.32.112:80 check
    server 7042-web-02 35.173.233.231:80 check
HAPROXY

sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

service haproxy restart
