#!/usr/bin/env bash
# Installs and configures Nginx on a new Ubuntu machine
apt-get update -y
apt-get install nginx -y
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
service nginx restart
