#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx
# /redirect_me returns a 301 Moved Permanently redirect

apt-get update -y
apt-get install -y nginx

# Use sed to replace the default location block line with redirect config
sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-available/default

service nginx restart
