#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx
# Custom 404 page containing "Ceci n'est pas une page"

apt-get update -y
apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Use sed to add redirect and custom 404 error page configuration
sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-available/default
sed -i 's|server_name _;|server_name _;\n\terror_page 404 /404.html;|' /etc/nginx/sites-available/default

service nginx restart
